default_context:
  project_name: 'storage_system'
  project_slug: 'storage_system'
  domain_main: 'storage_system.com'
  domain_staging: 'stag.storage_system.com'
  docker_swarm_stack_name_main: 'storage_system-com'
  docker_swarm_stack_name_staging: 'stag-storage_system-com'
  secret_key: 'storage'
  first_superuser: 'admin@storage_system.com'
  first_superuser_password: '906565'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.storage_system.com", "https://stag.storage_system.com", "https://storage_system.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: 'Storage'
  smtp_password: '906565'
  smtp_emails_from_email: 'info@storage_system.com'
  postgres_password: '906565'
  pgadmin_default_user: 'admin@storage_system.com'
  pgadmin_default_user_password: '906565'
  traefik_constraint_tag: 'storage_system.com'
  traefik_constraint_tag_staging: 'stag.storage_system.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:906565'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
